config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :assignments

  resources :users

  resources :notifications

  resources :promotions

  resources :trials

  resources :tenants

  resources :trial_alerts

   root 'sessions#new'
   match '/trials_expire', to: 'trials#expire', via: 'get'
   match '/trials_all', to: 'trials#all',  via: 'get'
   match '/trials_non_expire', to: 'trials#non_expire',  via: 'get'
   match '/trials_search', to: 'trials#search',  via: 'get'
   match '/trials_calendar', to: 'trials#calendar',  via: 'get'
   match '/trials_assigned', to: 'trials#assigned_trials',  via: 'get'
   match '/tasks_assigned', to: 'tasks#assigned_tasks',  via: 'get'

   match '/dashboard', to: 'dashboards#index', via:'get'

   match '/users_all', to: 'users#all',  via: 'get'

   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
   get '/task_complete/:id', to: 'tasks#task_done', as: 'complete_task'

   get '/task_not_complete/:id', to: 'tasks#task_not_done', as: 'uncomplete_task'

   match '/tenants_search', to: 'tenants#search',  via: 'get'

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base

  has_many :generic_images, foreign_key: :generic_id, dependent: :destroy
  accepts_nested_attributes_for :generic_images

  validates :nombre, presence: true
  validates :apellido_paterno, presence: true
  validates :apellido_materno, presence: true

  def self.created_today
    where('created_at >= ?', 1.day.ago)
  end

  def self.updated_today
    where('updated_at >= ? AND updated_at != created_at', 1.day.ago)
  end

  def self.generalSearch(search)
    sql=""
    search.split(" ").each_with_index do |val, index|
      unless index == search.split(" ").size - 1
        sql = "#{sql} nombre   LIKE '%#{val}%'  OR apellido_paterno LIKE  '%#{val}%' OR apellido_materno LIKE  '%#{val}%' OR telefono_casa LIKE  '%#{val}%' OR telefono_movil LIKE  '%#{val}%' OR delegacion LIKE  '%#{val}%' OR codigo_postal LIKE  '%#{val}%' OR no_exterior LIKE  '%#{val}%' OR colonia LIKE  '%#{val}%' OR ciudad LIKE  '%#{val}%' OR domicilio LIKE  '%#{val}%' OR curp LIKE  '%#{val}%' OR ife LIKE  '%#{val}%' OR estado_civil LIKE  '%#{val}%' OR nombre_aval LIKE  '%#{val}%' OR"
      else
        sql = "#{sql} nombre   LIKE '%#{val}%'  OR apellido_paterno LIKE  '%#{val}%' OR apellido_materno LIKE  '%#{val}%' OR telefono_casa LIKE  '%#{val}%' OR telefono_movil LIKE  '%#{val}%' OR delegacion LIKE  '%#{val}%' OR codigo_postal LIKE  '%#{val}%' OR no_exterior LIKE  '%#{val}%' OR colonia LIKE  '%#{val}%' OR ciudad LIKE  '%#{val}%' OR domicilio LIKE  '%#{val}%' OR curp LIKE  '%#{val}%' OR ife LIKE  '%#{val}%' OR estado_civil LIKE  '%#{val}%' OR nombre_aval LIKE  '%#{val}%'"
      end
    end
    where(sql)
  end

  def self.recents
    where('created_at >= ? OR updated_at >= ?',5.day.ago, 5.day.ago).limit(15)
  end

  def self.search(search)
    if search
      generalSearch(search)
    else
      recents
    end
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user

  # GET /tenants
  # GET /tenants.json
  def index
    @tenants = Tenant.all
    @createdTenants = Tenant.created_today
    @updatedTenants = Tenant.updated_today
  end

  def search
    @tenants = Tenant.search(params[:search])
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tenant_params
      params.require(:tenant).permit(:nombre, :apellido_paterno, :apellido_materno, :domicilio, :calle, :no_interior, :no_exterior, :colonia, :ciudad, :estado, :codigo_postal, :municipio, :delegacion, :telefono_casa, :telefono_movil, :curp, :ife, :estado_civil, :arrendador_actual, :arrendador_anterior, :domicilio_anterior, :nombre_aval, :domicilio_aval, :telefono_aval,:search)
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%- model_class = Tenant -%>
<div class="row">
  <div class="col-md-12">
    <% if @tenant.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">Existen Errores:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @tenant.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= form_for @tenant, :html => { :class => "form-horizontal tenant" } do |f| %>
<div class='row'>
  <div class='col-md-12'>
    <h2>Nombre del Arrendado</h2>
  </div>
  <div class='col-lg-12'>
    <div class="form-group">
      <div class="col-md-4 col-lg-4">
        <%= f.label :nombre, :class => 'control-label' %>
        <%= f.text_field :nombre, :class => 'form-control' %>
      </div>
      <div class="col-md-4 col-lg-4">
        <%= f.label :apellido_paterno, :class => 'control-label' %>
        <%= f.text_field :apellido_paterno, :class => 'form-control' %>
      </div>
      <div class="col-md-4 col-lg-4">
        <%= f.label :apellido_materno, :class => 'control-label' %>
        <%= f.text_field :apellido_materno, :class => 'form-control' %>
      </div>
    </div>
  </div>

  <div class='col-md-12'>
    <div class='divider'></div>

    <h2>Dirección del Arrendado</h2>
  </div>
  <div class='col-lg-12'>
    <div class="form-group">
      <div class="col-md-4">
        <%= f.label :domicilio, :class => 'control-label' %>
        <%= f.text_field :domicilio, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :calle, :class => 'control-label' %>
        <%= f.text_field :calle, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :no_interior, :class => 'control-label' %>
        <%= f.text_field :no_interior, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :no_exterior, :class => 'control-label' %>
        <%= f.text_field :no_exterior, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :colonia, :class => 'control-label' %>
        <%= f.text_field :colonia, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :ciudad, :class => 'control-label' %>
        <%= f.text_field :ciudad, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :estado, :class => 'control-label' %>
        <%= f.text_field :estado, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :codigo_postal, :class => 'control-label' %>
        <%= f.text_field :codigo_postal, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :municipio, :class => 'control-label' %>
        <%= f.text_field :municipio, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :delegacion, :class => 'control-label' %>
        <%= f.text_field :delegacion, :class => 'form-control' %>
      </div>
    </div>
  </div>
  <div class='col-md-12'>
    <div class='divider'></div>
    <h2>Información del Arrendado</h2>
  </div>
  <div class="col-lg-12">
    <div class="form-group">
      <div class="col-md-4">
        <%= f.label :telefono_casa, :class => 'control-label' %>
        <%= f.text_field :telefono_casa, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :telefono_movil, :class => 'control-label' %>
        <%= f.text_field :telefono_movil, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :curp, :class => 'control-label' %>
        <%= f.text_field :curp, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :ife, :class => 'control-label' %>
        <%= f.text_field :ife, :class => 'form-control' %>
      </div>
      <div class="col-md-4">
        <%= f.label :estado_civil, :class => 'control-label' %>
        <%= f.text_field :estado_civil, :class => 'form-control' %>
      </div>
      <div class="col-md-6">
        <%= f.label :domicilio_anterior, :class => 'control-label' %>
        <%= f.text_field :domicilio_anterior, :class => 'form-control' %>
      </div>
    </div>
  </div>
  <div class='col-md-12'>
    <div class='divider'></div>
    <h2>Información de Arrendador</h2>
  </div>
  <div class="col-lg-12">
    <div class="form-group">
      <div class="col-md-6">
        <%= f.label :arrendador_actual, :class => 'control-label' %>
        <%= f.text_field :arrendador_actual, :class => 'form-control' %>
      </div>
      <div class="col-md-6">
          <%= f.label :arrendador_anterior, :class => 'control-label' %>
          <%= f.text_field :arrendador_anterior, :class => 'form-control' %>
      </div>
    </div>
  </div>
  <div class='col-md-12'>
    <div class='divider'></div>
    <h2>Información del Aval</h2>
  </div>
  <div class="col-lg-12">
    <div class="form-group">
      <div class="col-md-6">
        <%= f.label :nombre_aval, :class => 'control-label' %>
        <%= f.text_field :nombre_aval, :class => 'form-control' %>
      </div>

      <div class="col-md-6">
        <%= f.label :telefono_aval, :class => 'control-label' %>
        <%= f.text_field :telefono_aval, :class => 'form-control' %>
      </div>
      <div class="col-md-6">
        <%= f.label :domicilio_aval, :class => 'control-label' %>
        <%= f.text_field :domicilio_aval, :class => 'form-control' %>
      </div>
    </div>
  </div>
</div>




<div class="divider"></div>
<div class='row'>
  <div class='col-md-4 col-xs-4 text-center'>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), trials_path, :class => 'btn btn-default' %>
  </div>
  <div class="col-md-4 col-xs-4"></div>
  <div class='col-md-4 col-xs-4 text-center'>
    <%= f.submit "Guardar", :class => 'btn btn-primary' %>
  </div>
</div>
<br>
<% end %>

app/views/tenants/_quick_table.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:arrendador_actual) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @tenants.each do |tenant| %>
    <tr>
      <td><%= "#{tenant.nombre} #{tenant.apellido_paterno}" %></td>
      <td><%= tenant.arrendador_actual %></td>
      <td>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
        edit_tenant_path(tenant), :class => 'btn btn-default btn-xs' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
        tenant_path(tenant),
        :method => :delete,
        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => '¿Esta Seguro que Quiere Borrarlo?')) },
        :class => 'btn btn-xs btn-danger' %>


        <%= link_to t('.show', :default => t("helpers.links.show")),
        tenant_path(tenant),
        :class => 'btn btn-xs btn-info' %>

      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tenants/all.html.erb
<h1>Listing tenants</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido paterno</th>
      <th>Apellido materno</th>
      <th>Domicilio</th>
      <th>Calle</th>
      <th>No interior</th>
      <th>No exterior</th>
      <th>Colonia</th>
      <th>Ciudad</th>
      <th>Estado</th>
      <th>Codigo postal</th>
      <th>Municipio</th>
      <th>Delegacion</th>
      <th>Telefono casa</th>
      <th>Telefono movil</th>
      <th>Curp</th>
      <th>Ife</th>
      <th>Estado civil</th>
      <th>Arrendador actual</th>
      <th>Arrendador anterior</th>
      <th>Domicilio anterior</th>
      <th>Nombre aval</th>
      <th>Domicilio aval</th>
      <th>Telefono aval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tenants.each do |tenant| %>
    <tr>
      <td><%= tenant.nombre %></td>
      <td><%= tenant.apellido_paterno %></td>
      <td><%= tenant.apellido_materno %></td>
      <td><%= tenant.domicilio %></td>
      <td><%= tenant.calle %></td>
      <td><%= tenant.no_interior %></td>
      <td><%= tenant.no_exterior %></td>
      <td><%= tenant.colonia %></td>
      <td><%= tenant.ciudad %></td>
      <td><%= tenant.estado %></td>
      <td><%= tenant.codigo_postal %></td>
      <td><%= tenant.municipio %></td>
      <td><%= tenant.delegacion %></td>
      <td><%= tenant.telefono_casa %></td>
      <td><%= tenant.telefono_movil %></td>
      <td><%= tenant.curp %></td>
      <td><%= tenant.ife %></td>
      <td><%= tenant.estado_civil %></td>
      <td><%= tenant.arrendador_actual %></td>
      <td><%= tenant.arrendador_anterior %></td>
      <td><%= tenant.domicilio_anterior %></td>
      <td><%= tenant.nombre_aval %></td>
      <td><%= tenant.domicilio_aval %></td>
      <td><%= tenant.telefono_aval %></td>
      <td><%= link_to 'Show', tenant %></td>
      <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
      <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/edit.html.erb
<%- model_class = Tenant -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/tenants/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="page-header">Arrendados</h1>
  </div>


  <div class="col-lg-4 col-md-6">
    <div class="panel panel-green">
      <%= link_to trials_calendar_path do %>
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-home fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @createdTenants.count %></div>
            <div>Arrendados Creados el Día de Hoy</div>
          </div>
        </div>
      </div>
      <a href="tenants/new">
        <div class="panel-footer">
          <span class="pull-left">Nuevo Arrendado</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      </a>
      <% end %>
    </div>
  </div>

  <div class="col-lg-4 col-md-6">
    <div class="panel panel-blue">
      <%= link_to tenants_search_path do %>

      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-search fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @tenants.count %></div>
            <div>En la base de datos</div>
          </div>
        </div>
      </div>
        <div class="panel-footer">
          <span class="pull-left">Buscar Arrendado</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>

</div>

app/views/tenants/new.html.erb
<%- model_class = Tenant -%>
<div class="page-header">
  <h1>Nuevo Arrendado</h1>
</div>
<%= render :partial => 'form' %>

app/views/tenants/search.html.erb
<%- model_class = Trial -%>

<div class="row">
  <div class='col-md-12'>
    <h1 class="page-header">Busqueda Arrendados</h1>
  </div>
</div>
<div class='row'>
<%= form_tag tenants_search_path, :method => 'get' do %>

<div class='col-md-6 col-xs-8'>
  <%= text_field_tag :search, nil ,:class => 'form-control'%>
</div>
<div class='col-md-3 col-xs-4'>
  <%= submit_tag "Search", :name => nil, :class => 'btn btn-default' %>
</div>
<% end %>
<br><br>
<div class='col-md-12'>
  <% if params[:search] %>
<h3>Resultados</h3>
<% else %>
<h3>Creados Recientemente</h3>
<% end %>
</div>
<div class='col-md-12'>
  <%= render 'quick_table', model_class: model_class%>
</div>

<% if @tenants.blank? %>
<div class='col-md-12'>
  <p><strong>No se encontraron Juicios</strong></p>
</div>
<% end %>
</div>
<div class='row'>
<div class="divider"></div>
<div class='row'>
  <div class='col-md-4 col-xs-4'>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), trials_path, :class => 'btn btn-default' %>
  </div>
  <div class="col-md-4 col-xs-4"></div>
  <div class='col-md-4 col-xs-4 text-center'>
  </div>
</div>
<br>
</div>

app/views/tenants/show.html.erb
<%- model_class = Tenant -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @tenant.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:apellido_paterno) %>:</strong></dt>
  <dd><%= @tenant.apellido_paterno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:apellido_materno) %>:</strong></dt>
  <dd><%= @tenant.apellido_materno %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domicilio) %>:</strong></dt>
  <dd><%= @tenant.domicilio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:calle) %>:</strong></dt>
  <dd><%= @tenant.calle %></dd>
  <dt><strong><%= model_class.human_attribute_name(:no_interior) %>:</strong></dt>
  <dd><%= @tenant.no_interior %></dd>
  <dt><strong><%= model_class.human_attribute_name(:no_exterior) %>:</strong></dt>
  <dd><%= @tenant.no_exterior %></dd>
  <dt><strong><%= model_class.human_attribute_name(:colonia) %>:</strong></dt>
  <dd><%= @tenant.colonia %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ciudad) %>:</strong></dt>
  <dd><%= @tenant.ciudad %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estado) %>:</strong></dt>
  <dd><%= @tenant.estado %></dd>
  <dt><strong><%= model_class.human_attribute_name(:codigo_postal) %>:</strong></dt>
  <dd><%= @tenant.codigo_postal %></dd>
  <dt><strong><%= model_class.human_attribute_name(:municipio) %>:</strong></dt>
  <dd><%= @tenant.municipio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:delegacion) %>:</strong></dt>
  <dd><%= @tenant.delegacion %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono_casa) %>:</strong></dt>
  <dd><%= @tenant.telefono_casa %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono_movil) %>:</strong></dt>
  <dd><%= @tenant.telefono_movil %></dd>
  <dt><strong><%= model_class.human_attribute_name(:curp) %>:</strong></dt>
  <dd><%= @tenant.curp %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ife) %>:</strong></dt>
  <dd><%= @tenant.ife %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estado_civil) %>:</strong></dt>
  <dd><%= @tenant.estado_civil %></dd>
  <dt><strong><%= model_class.human_attribute_name(:arrendador_actual) %>:</strong></dt>
  <dd><%= @tenant.arrendador_actual %></dd>
  <dt><strong><%= model_class.human_attribute_name(:arrendador_anterior) %>:</strong></dt>
  <dd><%= @tenant.arrendador_anterior %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domicilio_anterior) %>:</strong></dt>
  <dd><%= @tenant.domicilio_anterior %></dd>
  <dt><strong><%= model_class.human_attribute_name(:nombre_aval) %>:</strong></dt>
  <dd><%= @tenant.nombre_aval %></dd>
  <dt><strong><%= model_class.human_attribute_name(:domicilio_aval) %>:</strong></dt>
  <dd><%= @tenant.domicilio_aval %></dd>
  <dt><strong><%= model_class.human_attribute_name(:telefono_aval) %>:</strong></dt>
  <dd><%= @tenant.telefono_aval %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              tenants_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_tenant_path(@tenant), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              tenant_path(@tenant),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>