config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :assignments

  resources :users

  resources :notifications

  resources :promotions

  resources :trials

  resources :tenants

  resources :trial_alerts

   root 'sessions#new'
   match '/trials_expire', to: 'trials#expire', via: 'get'
   match '/trials_all', to: 'trials#all',  via: 'get'
   match '/trials_non_expire', to: 'trials#non_expire',  via: 'get'
   match '/trials_search', to: 'trials#search',  via: 'get'
   match '/trials_calendar', to: 'trials#calendar',  via: 'get'
   match '/trials_assigned', to: 'trials#assigned_trials',  via: 'get'
   match '/tasks_assigned', to: 'tasks#assigned_tasks',  via: 'get'

   match '/dashboard', to: 'dashboards#index', via:'get'

   match '/users_all', to: 'users#all',  via: 'get'

   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
   get '/task_complete/:id', to: 'tasks#task_done', as: 'complete_task'

   get '/task_not_complete/:id', to: 'tasks#task_not_done', as: 'uncomplete_task'

   match '/tenants_search', to: 'tenants#search',  via: 'get'

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true

  validates :user_id, presence: true


  def self.created_today
    where('created_at >= ?', 1.day.ago)
  end

  def self.task_not_done(session,privileges)
    privileges == "1"? where("done = 'f'") : where("user_id = ? AND done = 'f'",session)
  end

  def self.task_done(session,privileges)
    privileges == "1"? where("done = 't'") : where("user_id = ? AND done = 't'",session)
  end


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :task_done ,:task_not_done]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @createdTasks = Task.created_today.count
    @myTasks = Task.task_not_done(session[:user_id],session[:user_privileges]).count
  end

  def task_done
    if @task.update_attributes(done: 1)
      respond_to do |format|
        format.html do
          redirect_to tasks_assigned_path
          flash[:success]= 'Tarea Completada'
        end
      end
    end
  end

  def task_not_done
    if @task.update_attributes(done: 0)
      respond_to do |format|
        format.html do
          redirect_to tasks_assigned_path
         flash[:success]= 'Tarea NO Completada'
        end
      end
    end
  end


  def assigned_tasks
    Task.where(user_id: nil).destroy_all
    @unfinishedTasks = Task.task_not_done(session[:user_id],session[:user_privileges])
    @finishedTasks = Task.task_done(session[:user_id],session[:user_privileges]).limit(15)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.done = 0
    respond_to do |format|
      if @task.save
        format.html do
         redirect_to tasks_assigned_path
         flash[:success] ='Task was successfully created.'
       end
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html do
          redirect_to @task
          flash[:success] = 'Actualizada con Exito'
        end
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html do
        redirect_to tasks_url
        flash[:success] = 'Borrada con Exito!'
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:user_id,:description,:title)

    end
end

app/helpers/tasks_helper.rb
module TasksHelper

  def localeChange(date)
    Time.parse(date.to_s).strftime('%d-%m-%Y')
  end
end

app/views/tasks/_form.html.erb
<%- model_class = Task -%>
<div class="row">

  <div class="col-md-12">
    <% if @task.errors.any? %>
      <div id="error_expl" class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title">Existen Errores:</h3>
        </div>
        <div class="panel-body">
          <ul>
          <% @task.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= form_for(@task) do |f| %>
  <div class='row'>
    <div class='col-md-12'>
      <h2>Asignar a:</h2>
    </div>
    <%=  f.collection_radio_buttons :user_id, User.all, :id, :name do |b| %>
      <div class='col-md-4 col-sm-6 col-xs-12 text-center'>
        <%= b.label { b.radio_button +  b.text } %>
      </div>
    <% end %>
  </div>
  <div class="divider"></div>

  <div class="row">
    <div class="col-md-6">
      <%= f.label :title, :class => 'control-label' %>
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <div class='col-md-6'>
      <%= f.label :description, :class => 'control-label' %>
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
  </div>
  <div class="divider"></div>
  <div class='row'>
    <div class="col-md-12 actions text-center">
      <%= f.submit "Guardar", :class => 'btn btn-primary'%>
    </div>
  </div>
<% end %>

app/views/tasks/all.html.erb
<h1>Listing tasks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/assigned_tasks.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12">
    <div class='col-md-12'>
      <h1 class="page-header">Tareas</h1>
    </div>
  </div>
</div>

<div class="row">

  <div class='col-md-6'>
    <div class='col-md-12'>
      <h2>Pendientes</h2>
    </div>
  <table class="table table-condensed">
      <thead>
        <tr>
          <th>Accion</th>

          <th>Titulo</th>
          <th>Descripción</th>
          <th>
            Responsable
          </th>
        </tr>
      </thead>
      <% @unfinishedTasks.each do |task| %>
      <tr>
        <td>
          <%= link_to complete_task_path(task) do %><i class="fa fa-check"></i> <% end %>
        </td>
        <td>
          <%= task.title %>
        </td>
        <td>
          <%= task.description %>
        </td>

        <td>
          <%= task.user.name %>
        </td>
      </tr>
    <% end %>
  </table>
  </div>

<div class='col-md-6'>
  <div class='col-md-12'>
    <h2>Terminadas</h2>
  </div>
<table class="table table-condensed">
    <thead>
      <tr>
        <th>Accion</th>
        <th>Titulo</th>
        <th>Descripción</th>
        <th>
          Responsable
        </th>
      </tr>
    </thead>
    <% @finishedTasks.each do |task| %>
    <tr>
      <td>
        <%= link_to uncomplete_task_path(task) do %><i class="fa fa-times"></i> <% end %>
      </td>
      <td>
        <%= task.title %>
      </td>
      <td>
        <%= task.description %>
      </td>
      <td>
        <%= task.user.name %>
      </td>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12">
    <div class='col-md-12'>
      <h1 class="page-header">Tareas</h1>
    </div>
  </div>
</div>

<div class='row'>
  <div class="col-lg-3 col-md-6">

    <div class="panel panel-green">
      <%= link_to new_task_path do %>

      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-check-square-o fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @createdTasks %></div>
            <div>Creadas el Día de Hoy</div>
          </div>
        </div>
      </div>
        <div class="panel-footer">
          <span class="pull-left">Nueva Tarea</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <%= link_to tasks_assigned_path do %>

      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-list-ul fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @myTasks %></div>
            <div>Asignadas</div>
          </div>
        </div>
      </div>
        <div class="panel-footer">
          <span class="pull-left">Ver Tareas</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class='col-md-12'>
    <h1 class="page-header">Nueva Tarea</h1>
  </div>
</div>
<%= render :partial => 'form' %>

app/views/tasks/show.html.erb
<%- model_class = Trial -%>
<div class="row">
  <div class='col-md-12 col-xs-12'>
    <h1 class="page-header">Viendo Tarea</h1>
  </div>
</div>

<div class='row'>
  <div class='col-md-12'>
    <h3>Asignado</h3>
  </div>
  <div class='col-md-4 col-sm-6 col-xs-12 text-center'>
    <%= @task.user.name %>
  </div>
</div>
<div class="divider"></div>
<div class="row">
  <div class="col-md-4 text-center">
    <h3>Estado</h3>
    <% if @task.done %>
    <p>
      Terminada
    </p>
    <% else %>
    <p>
      En Proceso
    </p>
    <% end %>
  </div>
  <div class="col-md-4 text-center">
    <h3>Titulo</h3>
    <%= @task.title %>
  </div>
  <div class="col-md-4 text-center">
    <h3>Descripción</h3>
    <%= @task.description %>
  </div>
</div>
<div class="divider"></div>
<div class='row'>
  <div class='col-md-4 col-xs-4 text-center'>
    <%= link_to t('.back', :default => t("helpers.links.back")),
    tasks_path, :class => 'btn btn-default'  %>
  </div>
  <div class="col-md-4 col-xs-4"></div>
  <div class='col-md-4 col-xs-4 text-center'>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
      edit_task_path(@task), :class => 'btn btn-default' %>
  </div>
</div>