config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :assignments

  resources :users

  resources :notifications

  resources :promotions

  resources :trials

  resources :tenants

  resources :trial_alerts

   root 'sessions#new'
   match '/trials_expire', to: 'trials#expire', via: 'get'
   match '/trials_all', to: 'trials#all',  via: 'get'
   match '/trials_non_expire', to: 'trials#non_expire',  via: 'get'
   match '/trials_search', to: 'trials#search',  via: 'get'
   match '/trials_calendar', to: 'trials#calendar',  via: 'get'
   match '/trials_assigned', to: 'trials#assigned_trials',  via: 'get'
   match '/tasks_assigned', to: 'tasks#assigned_tasks',  via: 'get'

   match '/dashboard', to: 'dashboards#index', via:'get'

   match '/users_all', to: 'users#all',  via: 'get'

   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
   get '/task_complete/:id', to: 'tasks#task_done', as: 'complete_task'

   get '/task_not_complete/:id', to: 'tasks#task_not_done', as: 'uncomplete_task'

   match '/tenants_search', to: 'tenants#search',  via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base

  before_save { username.downcase! }
  has_many :assignments
  has_many :trials, through: :assigments


  has_many :tasks


  validates :username, presence: true
  validates :name, presence: true
  validates :privileges, presence: true
  has_secure_password


  def self.created_today
    where('created_at >= ?', 1.day.ago)
  end

  def self.non_admin(session)
    where('privileges != ? AND id != ?', "1", session)
  end

  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_digest)
      user
    else
      nil
    end
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :admin_zone, only: [:new, :edit, :destroy]

  # GET /users
  # GET /users.json
  def index
    @createdUsers = User.created_today.count
    @users = User.all.count

  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def all
    @users = User.all
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :password, :privileges)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <div class="row">
    <div class='col-md-4'></div>
    <div class='form-group'>
      <div class='col-md-4'>
        <%= f.label :name, "Nombre" %>
        <%= f.text_field :name, class: 'form-control' %>
        <% if @user.errors[:name].present? %>
          <p class=" alert-danger" role="alert">
            <i class="fa fa-times-circle"></i>
            <%= @user.errors[:name].join(' ') %>
          </p>
        <% end %>
        <%= f.label :username, "Nombre de Usuario" %>
        <%= f.text_field :username, class: 'form-control' %>

        <% if @user.errors[:username].present? %>
          <p class=" alert-danger" role="alert">
            <i class="fa fa-times-circle"></i>
            <%= @user.errors[:username].join(' ') %>
          </p>
        <% end %>
        <%= f.label :password, "Contraseña" %>
        <%= f.password_field :password, class: 'form-control' %>
        <% if @user.errors[:password].present? %>
          <p class=" alert-danger" role="alert">
            <i class="fa fa-times-circle"></i>
            <%= @user.errors[:password].join(' ') %>
          </p>
        <% end %>
        <%= f.label :password_confirmation, "Confirmación de la Contraseña" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <% if @user.errors[:password_confirmation].present? %>
          <p class=" alert-danger" role="alert">
            <i class="fa fa-times-circle"></i>
            <%= @user.errors[:password_confirmation].join(' ') %>
          </p>
        <% end %>
        <%= f.label "Privilegios" %>
        <br>
        <%= f.select(:privileges, [['Admin', 1], ['Empleado', 2], ['Consultor', 3]]) %>

        <% if @user.errors[:privileges].present? %>
          <p class=" alert-danger" role="alert">
            <i class="fa fa-times-circle"></i>
            <%= @user.errors[:privileges].join(' ') %>
          </p>
        <% end %>
      </div>
    </div>
    <div class='col-md-4'></div>
    <div class='col-md-12 text-center'>
      <br>
      <%= f.submit "Guardar", :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/users/all.html.erb
<h1>Usuarios</h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Ver', user %></td>
        <td><%= link_to 'Editar', edit_user_path(user) %></td>
        <td><%= link_to 'Destruir', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/edit.html.erb
<div class="row">
  <div class='col-md-12'>
    <h1 class="page-header">Editar Usuario</h1>
  </div>
</div>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12">
    <div class='col-md-12'>
      <h1 class="page-header">Usuarios</h1>
    </div>
  </div>
</div>
<div class='row'>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-green">
      <%= link_to new_user_path do %>
      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-user fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @createdUsers %></div>
            <div>Creados el Día de Hoy</div>
          </div>
        </div>
      </div>
        <div class="panel-footer">
          <span class="pull-left">Nuevo Usuario</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-blue">
      <%= link_to users_all_path do %>

      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-search fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @users %></div>
            <div>En la base de datos</div>
          </div>
        </div>
      </div>
        <div class="panel-footer">
          <span class="pull-left">Buscar Usuarios</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-lg-3 col-md-6">
    <div class="panel panel-red">
      <%= link_to trials_calendar_path do %>

      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-check-square-o fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @users %></div>
            <div>Tareas</div>
          </div>
        </div>
      </div>
        <div class="panel-footer">
          <span class="pull-left">Asignar Tareas</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-lg-3 col-md-6">
    <div class="panel panel-yellow">
      <%= link_to '/trials_expire' do %>

      <div class="panel-heading">
        <div class="row">
          <div class="col-xs-3">
            <i class="fa fa-list-ul fa-5x"></i>
          </div>
          <div class="col-xs-9 text-right">
            <div class="huge"><%= @updatedTrials %></div>
            <div>Asignados</div>
          </div>
        </div>
      </div>
        <div class="panel-footer">
          <span class="pull-left">Ver Calendario</span>
          <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class='col-md-12'>
    <h1 class="page-header">Nuevo Usuario</h1>
  </div>
</div>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-12">
    <h1>Usuario</h1>
  </div>

  <div class="col-md-4">
    <strong>Nombre:</strong>
    <%= @user.name %>
  </div>

  <div class="col-md-4">
    <strong>Username:</strong>
    <%= @user.username %>
  </div>
</div>