config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  resources :assignments

  resources :users

  resources :notifications

  resources :promotions

  resources :trials

  resources :tenants

  resources :trial_alerts

   root 'sessions#new'
   match '/trials_expire', to: 'trials#expire', via: 'get'
   match '/trials_all', to: 'trials#all',  via: 'get'
   match '/trials_non_expire', to: 'trials#non_expire',  via: 'get'
   match '/trials_search', to: 'trials#search',  via: 'get'
   match '/trials_calendar', to: 'trials#calendar',  via: 'get'
   match '/trials_assigned', to: 'trials#assigned_trials',  via: 'get'
   match '/tasks_assigned', to: 'tasks#assigned_tasks',  via: 'get'

   match '/dashboard', to: 'dashboards#index', via:'get'

   match '/users_all', to: 'users#all',  via: 'get'

   get    'login'   => 'sessions#new'
   post   'login'   => 'sessions#create'
   delete 'logout'  => 'sessions#destroy'
   get '/task_complete/:id', to: 'tasks#task_done', as: 'complete_task'

   get '/task_not_complete/:id', to: 'tasks#task_not_done', as: 'uncomplete_task'

   match '/tenants_search', to: 'tenants#search',  via: 'get'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

  <title>Ranking Info</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>


</head>

<body>

  <div id="wrapper">
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Ranking Info</a>
      </div>
      <!-- Top Menu Items -->
      <% if logged_in? %>
        <ul class="nav navbar-right top-nav">
          <li class="dropdown">

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell <% if countAssignedTasks >0 %>active <% end %>"></i> <b class="caret"></b></a>
            <ul class="dropdown-menu alert-dropdown">
              <li>
                <%= link_to tasks_assigned_path do %>
                  <% if session[:user_privileges] != "1" %>
                  <%= countAssignedTasks %> Tareas Asignadas
                  <% else %>
                    Ver Tareas
                  <% end %>
                <% end %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to trials_assigned_path do %>
                  <% if session[:user_privileges] != "1" %>
                  <%= countAssignedTrials %> Juicios Asignados
                  <% else %>
                    Ver Juicios
                  <% end %>
                <% end %>
              </li>
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= session[:user_name] %> <b class="caret"></b></a>
            <ul class="dropdown-menu">


              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        </ul>
      <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
            <li>
              <%= link_to dashboard_path do%><i class="fa fa-fw fa-dashboard"></i> Panel de Control <% end %>
            </li>
            <li>
              <%= link_to trials_path do%><i class="fa fa-fw fa-briefcase"></i> Juicios <% end %>
            </li>
            <li>
              <%= link_to tenants_path do%><i class="fa fa-fw fa-home"></i> Arrendados <% end %>
            </li>

            <li>
              <%= link_to users_path do%><i class="fa fa-fw fa-users"></i> Usuarios <% end %>
            </li>

            <li>
              <%= link_to tasks_path do%><i class="fa fa-fw fa-check-square-o"></i> Tareas <% end %>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      <% end %>
    </nav>
    <div id="page-wrapper">
      <div class="container-fluid">

        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "alert alert-#{key}") %>
        <% end %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>

      </div><!-- /.container-fluid -->
    </div><!-- /#page-wrapper -->
  </div><!-- /#wrapper -->
</body>
</html>